# Generated by Django 5.1.7 on 2025-03-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transaction_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
