# Generated by Django 5.1.7 on 2025-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
