# Generated by Django 5.1.7 on 2025-03-28 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_main_price_product_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('number_of_people', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_weekorders', to='products.product')),
                ('weekly_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_order_items', to='weekorder.weeklyorder')),
            ],
        ),
    ]
