# Generated by Django 5.1.7 on 2025-03-28 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_selling_price'),
        ('weekorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_week', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weekly_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_week', to='weekorder.weeklyorder'),
        ),
    ]
