# Generated by Django 5.1.7 on 2025-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekorder', '0003_weeklyorder_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
