# Generated by Django 5.1.7 on 2025-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekorder', '0004_weeklyorder_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyorder',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
