# Generated by Django 5.1.7 on 2025-03-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_customuser_balance_customuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_customer_id',
        ),
    ]
