# Generated by Django 5.1.7 on 2025-04-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_remove_customuser_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('delivery_man', 'Delivery Man')], db_index=True, default='user', max_length=100, null=True),
        ),
    ]
